version: 2
updates:
  - package-ecosystem: pip
    labels:
      - dependencies
    directory: backend/
    schedule:
      interval: weekly
  - package-ecosystem: docker
    labels:
      - dependencies
    directory: backend/
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - CI/CD
      - dependency
