version: 2
updates:
  - package-ecosystem: pip
    labels:
      - dependencies
    directories:
      - backend/
      - client/python/
      - bot/?*/
    schedule:
      interval: weekly
  - package-ecosystem: docker
    labels:
      - dependencies
    directories:
      - backend/
      - bot/*/
      - /
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - CI/CD
      - dependencies
