version: '3.8'

services:
  nginx:
    extends:
      file: docker-compose.yml
      service: nginx
    build:
      target: ssl
    image: spellbook-nginx-ssl
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/:ro
    ports:
      - 443:443
