version: '3.8'

services:
  nginx:
    extends:
      file: docker-compose.yml
      service: nginx
    build:
      target: ssl
    image: spellbook-nginx-ssl
    volumes:
      - ${SSL_CERTIFICATE_PATH:?}:/etc/nginx/ssl/cert.crt:ro
      - ${SSL_PRIVATEKEY_PATH:?}:/etc/nginx/ssl/cert.key:ro
    ports:
      - 443:443
