version: '3.8'

services:
  nginx:
    extends:
      file: docker-compose.yml
      service: nginx
    build:
      target: ssl
    image: spellbook-nginx-ssl
    volumes:
      - ${SSL_CERTIFICATE_LOCATION:?}:/etc/nginx/ssl/:ro
    ports:
      - 443:443
