version: '3.8'

services:
  web:
    build:
      context: .
      args:
        SECRET_KEY: hotdogs
    expose:
      - 8000
    depends_on:
      - db
    volumes:
      - static_volume:/home/app/web/staticfiles
    environment:
      SQL_ENGINE: django.db.backends.postgresql
      SQL_DATABASE: spellbook_db_prod
      SQL_USER: docker_compose
      SQL_PASSWORD: docker_compose
      SQL_HOST: db
      SQL_PORT: 5432
      DATABASE: postgres
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web
    volumes:
      - static_volume:/home/app/web/staticfiles
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      PGPORT: 5432
      POSTGRES_USER: docker_compose
      POSTGRES_PASSWORD: docker_compose
      POSTGRES_DB: spellbook_db_prod
volumes:
  static_volume:
  postgres_data:
