version: '3.8'

services:
  web:
    build:
      context: .
      args:
        SECRET_KEY: ${SECRET_KEY:?}
    expose:
      - 8000
    depends_on:
      - db
    volumes:
      - static_volume:/home/app/web/staticfiles
    environment:
      SQL_ENGINE: django.db.backends.postgresql
      SQL_DATABASE: spellbook_db_prod
      SQL_USER: ${DB_USER:?}
      SQL_PASSWORD: ${DB_PASSWORD:?}
      SQL_HOST: db
      SQL_PORT: 5432
      DATABASE: postgres
    restart: always
  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - web
    volumes:
      - static_volume:/home/app/web/staticfiles
    restart: always
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      PGPORT: 5432
      POSTGRES_USER: ${DB_USER:?}
      POSTGRES_PASSWORD: ${DB_PASSWORD:?}
      POSTGRES_DB: spellbook_db_prod
    restart: always
volumes:
  static_volume:
  postgres_data:
