version: '3.8'

services:
  web:
    build:
      context: .
      target: production
      args:
        SECRET_KEY: ${SECRET_KEY:-tmp_key}
    image: spellbook-backend
    ports:
      - 80:80
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
    environment:
      SQL_ENGINE: django.db.backends.postgresql
      SQL_DATABASE: spellbook_db_test
      SQL_USER: test_user
      SQL_PASSWORD: test_password
      SQL_HOST: db
      SQL_PORT: 5432
      DATABASE: postgres
    restart: always

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      PGPORT: 5432
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: spellbook_db_test
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -d spellbook_db_test -U test_user" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

volumes:
  postgres_data:
