name: CI/CD

on:
  push:
    branches:
      - "*"
  pull_request:
    types:
      - opened
      - reopened
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
        shell: bash
    env:
      SECRET_KEY: ci_build_secret
      DB_USER: ci_build_user
      DB_PASSWORD: ci_build_password
    steps:
      - uses: actions/checkout@v3
      - run: docker compose -f docker-compose.yml build
