name: CI/CD

on:
  push:
    branches:
      - "*"
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
        shell: bash
    steps:
      - uses: actions/checkout@v3
      - run: docker compose -f docker-compose.yml build
