name: CI/CD

on:
  push:
    branches:
      - "**"
    tags:
      - "*"
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      SECRET_KEY: ci_build_secret
      DB_USER: ci_build_user
      DB_PASSWORD: ci_build_password
    outputs:
      version: ${{ steps.semver.outputs.version }}
      should-release: ${{ steps.semver.outputs.should-release }}
      is-prerelease: ${{ steps.semver.outputs.is-github-prerelease }}
      can-deploy: 'false'
    steps:
      - id: semver
        name: Checkout
        uses: EasyDesk/action-semver-checkout@v1
      - run: docker compose -f docker-compose.yml build
        working-directory: backend
  release:
    runs-on: ubuntu-latest
    needs: build
    if: needs.build.outputs.should-release == 'true'
    concurrency: release
    steps:
      - name: Release
        uses: EasyDesk/action-semver-release@v1
        with:
          version: ${{ needs.build.outputs.version }}
          prerelease: ${{ needs.build.outputs.is-prerelease }}
          prefix: CSB
  deploy:
    runs-on: ubuntu-latest
    needs: release
    if: needs.build.outputs.can-deploy == 'true'
    concurrency: deploy
    environment: production
    steps:
      - run: arwynfr/actions-docker-context@v2
        with:
          docker_host: ssh://${{ secrets.USERNAME }}@${{ secrets.HOST }}
          context_name: production
          ssh_cert: ${{ secrets.HOST }} ${{ secrets.SSH_PUB }}
          ssh_key: ${{ secrets.SSH_KEY }}
      - run: docker --context remote ps
